
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20924612v
 */
public class ScoreBoard extends JLabel {

    /**
     * Creates new form ScoreBoard
     */
    private int score;
    
    public ScoreBoard() {
        super();
        score = 0;
        setText("Score: 0");
    }

    public void increment(int points) {

        score++;
        setText("Score: " + score);
    }

    public void reset() {

        score = 0;
        setText("Score: 0");
    }

    public int getScore() {
        return score;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setText("0");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
